source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPHelpViewController_Example', :exclusive => true do
  pod 'POPHelpViewController', :path => '../'
end

target 'POPHelpViewController_Tests', :exclusive => true do
  pod 'POPHelpViewController', :path => '../'

  
end
