source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPHelpViewController_Example' do
  pod 'POPHelpViewController', :path => '../'
  target 'POPHelpViewController_Tests' do
  	inherit! :search_paths
  end
end


